### ISSUE TITLE
Show thumbnails stuck on loading on Kali Linux.

### ISSUE THREAD

**Issue by PingLH** [NastuzziSamy/ulauncher-youtube-search#1]
Show thumbnails stuck on loading on Kali Linux.

![yt loading](https://user-images.githubusercontent.com/74230996/102033360-d8f56080-3d80-11eb-86db-37128663687b.jpg)

Turning off thumbnails makes the plugin work correctly. 

Are there any tweaks I could do to make the thumbnails work?

**Comment by NastuzziSamy** [comment]
Hi, I am adding an option to disable thumbnails.

Do you have any logs ?

**Comment by NastuzziSamy** [comment]
Nvm, I have found the issue, the directory was missing.

Update the extension and it will work @PingLH :)
