### ISSUE TITLE
yt cats or yt dogs loading .001% of the time

### ISSUE THREAD

**Issue by PingLH** [NastuzziSamy/ulauncher-youtube-search#2]
yt cats or yt dogs loading .001% of the time

running yt cats or yt dogs worked one time for each doing this for no thumbnail or thumbnail.

I tried this like over 30 or more times.
![yt cats no results](https://user-images.githubusercontent.com/74230996/102176213-9443f500-3e66-11eb-8e30-b4581c6c59c0.jpg)

I am new to Linux trying to switch over from windows. Learning about all the power app for Linux.

I love your add on for YouTube. 

Any way to make the searching... load faster with results?

Thank you.
P.S. the thumbnails are working now.
You Rock!

**Comment by NastuzziSamy** [comment]
Hi @PingLH , thank you again, YOU are breathtaking! haha

It is now fixed :)
