### ISSUE TITLE
Invisible titles

### ISSUE THREAD

**Issue by bedii97** [NastuzziSamy/ulauncher-youtube-search#3]
![Screenshot_20210314_012133](https://user-images.githubusercontent.com/20071561/111051398-bfd57c00-8463-11eb-9d23-d37e90aecc9c.png)

**Comment by NastuzziSamy** [comment]
Hey @bedii97, thank you for your issue.

It was fixed, the issue were when a search has "&" in its title, it does not show..
I replaced "&" by "and".
